import json
import logging
from typing import Dict, Any, Optional
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

class EvidenceCapture:
    """Capture evidence for compliance and audit trails"""

    def __init__(self, evidence_dir: str = "src/governance/evidence"):
        self.evidence_dir = evidence_dir
        Path(evidence_dir).mkdir(parents=True, exist_ok=True)

    def record_remediation(
        self,
        finding_id: str,
        remediation_id: str,
        policy_applied: str,
        policy_version: str,
        tier: int,
        code_before: str,
        code_after: str,
        model_used: str,
        confidence_score: float,
        tests_passed: bool,
        sast_passed: bool,
        approval_chain: list,
        approval_by: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Record complete remediation evidence for compliance.

        Args:
            finding_id: Original finding ID
            remediation_id: Unique remediation ID
            policy_applied: Policy filename (e.g., cwe_89_sqli.md)
            policy_version: Policy version
            tier: Remediation tier (1, 2, or 3)
            code_before: Original code
            code_after: Fixed code
            model_used: Claude model name
            confidence_score: AI confidence (0.0-1.0)
            tests_passed: Did tests pass?
            sast_passed: Did SAST re-scan pass?
            approval_chain: Required approvals
            approval_by: Who approved

        Returns:
            Evidence artifact (dict)
        """

        evidence = {
            "metadata": {
                "remediation_id": remediation_id,
                "finding_id": finding_id,
                "timestamp": datetime.now().isoformat(),
                "evidence_version": "1.0"
            },
            "what_changed": {
                "file": "TBD",  # Set by caller
                "code_before": code_before,
                "code_after": code_after,
                "lines_changed": len(code_after.split('\n')) - len(code_before.split('\n'))
            },
            "why_changed": {
                "cwe_id": int(policy_applied.split('_')[1]) if '_' in policy_applied else None,
                "policy_applied": policy_applied,
                "policy_version": policy_version,
                "policy_tier": tier,
                "institutional_requirement": f"Remediation per {policy_applied} Tier {tier}"
            },
            "who_changed_it": {
                "model": model_used,
                "model_version": model_used.split('-')[-1],
                "system_prompt_version": "appsec-v2.1",
                "framework": "Claude Agent"
            },
            "when": {
                "timestamp": datetime.now().isoformat(),
                "timezone": "UTC"
            },
            "how_confident": {
                "ai_confidence_score": confidence_score,
                "confidence_level": self._confidence_level(confidence_score),
                "reasoning": f"Score {confidence_score:.0%}: Based on pattern matching, test results, and policy compliance"
            },
            "compliance": {
                "tests_passed": tests_passed,
                "sast_passed": sast_passed,
                "policy_compliant": sast_passed,  # SAST pass = policy compliant
                "approval_required": tier >= 2,
                "approval_chain": approval_chain,
                "approved_by": approval_by,
                "approval_timestamp": datetime.now().isoformat() if approval_by else None
            },
            "governance_tags": [
                f"ai-assisted:{model_used}",
                f"policy:{policy_applied}",
                f"tier:{tier}",
                f"confidence:{self._confidence_level(confidence_score)}",
                "automated-remediation"
            ]
        }

        # Save to disk
        self._save_evidence(remediation_id, evidence)

        return evidence

    def create_pr_comment(self, evidence: Dict[str, Any]) -> str:
        """
        Create a PR comment with AI-assisted markers and evidence.

        Returns:
            Markdown comment for GitHub PR
        """

        comment = f"""## 🤖 AI-Assisted Security Remediation

This fix was generated by Claude AI following organizational security policies.

### Evidence Summary

| Aspect | Details |
|--------|---------|
| **AI Model** | {evidence['who_changed_it']['model']} |
| **Confidence** | {evidence['how_confident']['confidence_level']} ({evidence['how_confident']['ai_confidence_score']:.0%}) |
| **Policy Applied** | {evidence['why_changed']['policy_applied']} v{evidence['why_changed']['policy_version']} |
| **Remediation Tier** | Tier {evidence['why_changed']['policy_tier']} |
| **Tests** | {'✅ All Passed' if evidence['compliance']['tests_passed'] else '❌ Some Failed'} |
| **SAST Re-scan** | {'✅ Clear' if evidence['compliance']['sast_passed'] else '❌ Issues Found'} |

### What Changed

**Before:**
```
{evidence['what_changed']['code_before']}
```

**After:**
```
{evidence['what_changed']['code_after']}
```

### Why This Fix

- **Institutional Requirement**: {evidence['why_changed']['institutional_requirement']}
- **Policy Tier**: {evidence['why_changed']['policy_tier']} (requires {'developer review' if evidence['why_changed']['policy_tier'] == 1 else 'code review' if evidence['why_changed']['policy_tier'] == 2 else 'architecture review'})
- **Reasoning**: {evidence['how_confident']['reasoning']}

### Validation Checklist

- [{'x' if evidence['compliance']['tests_passed'] else ' '}] Existing tests pass ({evidence['compliance']['tests_passed']})
- [{'x' if evidence['compliance']['sast_passed'] else ' '}] SAST re-scan passes ({evidence['compliance']['sast_passed']})
- [{'x' if evidence['compliance']['sast_passed'] else ' '}] Security test passes (injection blocked)
- [{'x' if evidence['compliance']['policy_compliant'] else ' '}] Complies with policy ({evidence['compliance']['policy_compliant']})

### Approval Required

- **Chain**: {' → '.join(evidence['compliance']['approval_chain'])}
- **Status**: {'✅ Approved by: ' + evidence['compliance']['approved_by'] if evidence['compliance']['approved_by'] else '⏳ Awaiting approval'}

### For Compliance

```json
{{
  "remediation_id": "{evidence['metadata']['remediation_id']}",
  "finding_id": "{evidence['metadata']['finding_id']}",
  "policy": "{evidence['why_changed']['policy_applied']}",
  "policy_version": "{evidence['why_changed']['policy_version']}",
  "model": "{evidence['who_changed_it']['model']}",
  "confidence_score": {evidence['how_confident']['ai_confidence_score']},
  "timestamp": "{evidence['when']['timestamp']}",
  "tests_passed": {str(evidence['compliance']['tests_passed']).lower()},
  "sast_passed": {str(evidence['compliance']['sast_passed']).lower()}
}}
```

---

🤖 **Generated by Claude Agent** | 📋 **Policy-Driven Remediation** | ✅ **Governance-Aware**
"""

        return comment

    def _confidence_level(self, score: float) -> str:
        """Map confidence score to level"""
        if score >= 0.95:
            return "Very High"
        elif score >= 0.90:
            return "High"
        elif score >= 0.80:
            return "Medium"
        else:
            return "Low"

    def _save_evidence(self, remediation_id: str, evidence: Dict[str, Any]):
        """Save evidence to JSON file"""
        filepath = Path(self.evidence_dir) / f"{remediation_id}.json"
        with open(filepath, 'w') as f:
            json.dump(evidence, f, indent=2, default=str)
        logger.info(f"Evidence saved: {filepath}")


# Test usage
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    logger.info("Testing Governance Logger\n")

    capture = EvidenceCapture()

    # Record a remediation
    evidence = capture.record_remediation(
        finding_id="checkmarx-2026-04-02-001",
        remediation_id="rem-2026-04-02-001",
        policy_applied="cwe_89_sqli.md",
        policy_version="2.1",
        tier=1,
        code_before='query = f"SELECT * FROM users WHERE id={user_id}"',
        code_after='"SELECT * FROM users WHERE id=?", [user_id]',
        model_used="claude-sonnet-4.6",
        confidence_score=0.97,
        tests_passed=True,
        sast_passed=True,
        approval_chain=["developer"],
        approval_by="dev@company.com"
    )

    print("✓ Evidence recorded")
    print(f"  Confidence: {evidence['how_confident']['confidence_level']}")
    print(f"  Policy: {evidence['why_changed']['policy_applied']}")

    # Generate PR comment
    pr_comment = capture.create_pr_comment(evidence)
    print("\n✓ PR Comment generated:")
    print(pr_comment[:200] + "...\n")
