"""
AI-Assisted PR markers and labels for GitHub.

These markers help developers and reviewers understand:
- This fix was AI-generated
- What policy it follows
- How confident the AI was
- What validations passed
"""

class PRMarkers:
    """Create PR labels and status checks for AI-assisted fixes"""

    # GitHub PR Labels
    LABELS = {
        "ai-generated": {
            "description": "Fix generated by AI model",
            "color": "0366d6"  # Blue
        },
        "security-remediation": {
            "description": "Security vulnerability fix",
            "color": "d73a49"  # Red
        },
        "policy-enforced": {
            "description": "Fix complies with security policy",
            "color": "28a745"  # Green
        },
        "high-confidence": {
            "description": "High confidence AI fix (>90%)",
            "color": "28a745"  # Green
        },
        "requires-review": {
            "description": "Requires code review before merge",
            "color": "ffd700"  # Gold
        },
    }

    # Status Check Formats
    @staticmethod
    def create_status_check(
        model: str,
        confidence: float,
        policy: str,
        tests_passed: bool,
        sast_passed: bool
    ) -> str:
        """Create GitHub status check for PR"""

        status = "✅ pass" if (tests_passed and sast_passed) else "❌ fail"
        confidence_emoji = "🟢" if confidence > 0.90 else "🟡" if confidence > 0.80 else "🔴"

        return f"""
### 🤖 AI Remediation Status

{confidence_emoji} **Confidence**: {confidence:.0%}
📋 **Policy**: {policy}
✅ **Tests**: {'PASS' if tests_passed else 'FAIL'}
✅ **SAST**: {'PASS' if sast_passed else 'FAIL'}

**Status**: {status}
"""

    @staticmethod
    def get_labels_for_fix(tier: int, confidence: float) -> list:
        """Get labels based on fix characteristics"""
        labels = [
            "ai-generated",
            "security-remediation",
            "policy-enforced"
        ]

        if confidence > 0.90:
            labels.append("high-confidence")

        if tier >= 2:
            labels.append("requires-review")

        return labels


# Usage:
# labels = PRMarkers.get_labels_for_fix(tier=1, confidence=0.97)
# status = PRMarkers.create_status_check(...)
